package_manager: npm_and_yarn
dependency_updates:
  - name: lodash.merge
    ignore_versions: '> 4.6.2'
    commit_message: |-
      [Security] Bump lodash.merge from 4.6.0 to 4.6.2
      Bumps [lodash.merge](https://github.com/lodash/lodash) from 4.6.0 to 4.6.2. **This update includes security fixes.**
      - [Release notes](https://github.com/lodash/lodash/releases)
      - [Commits](https://github.com/lodash/lodash/commits)
  - name: lodash
    ignore_versions: '> 4.17.15'
    commit_message: |-
      [Security] Bump lodash from 4.17.11 to 4.17.13
      Bumps [lodash](https://github.com/lodash/lodash) from 4.17.11 to 4.17.13. **This update includes security fixes.**
      - [Release notes](https://github.com/lodash/lodash/releases)
      - [Commits](lodash/lodash@4.17.11...4.17.13)
